apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: excalidraw-cert
  namespace: excalidraw
spec:
  secretName: excalidraw-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - excalidraw.bhavyasachdeva.in
